### ISSUE TITLE
Emoncms http posting incorrectly reports "connected: no"

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#18]
Posting to Emoncms (emonPi) via http / https works great but even when successfully posting the interface still reports `Connected: No` and debug log reports `Emoncms error: {"
success": true}`

![Screenshot 2019-09-07 at 14 23 13](https://user-images.githubusercontent.com/758844/64475487-56442580-d17b-11e9-9f0f-539af438cde2.png)

![Screenshot 2019-09-07 at 14 25 50](https://user-images.githubusercontent.com/758844/64475497-6b20b900-d17b-11e9-9207-de2e74d6deca.png)

Currently, I'm posting to an emonPi which does not support https, is https only enabled for emoncms.org and data.openevse?

**Comment by jeremypoulter** [comment]
The problem here is EmonCMS behaves differently locally vs emoncms.org;

'Post' to emoncms.org:
```
HTTP/1.1 200 OK
Date: Mon, 09 Sep 2019 09:48:54 GMT
Server: Apache/2.2.22 (Ubuntu)
X-Powered-By: PHP/5.3.10-1ubuntu3.25
Content-Length: 2
Connection: close
Content-Type: application/json

ok
```

Post to local EmonBase:
```
HTTP/1.1 200 OK
Date: Mon, 09 Sep 2019 09:50:11 GMT
Server: Apache/2.4.10 (Raspbian)
Content-Length: 17
Connection: close
Content-Type: text/plain;charset=UTF-8

{
  "success": true
}
```

If you can confirm that the HTTP code is 2xx if successful and 4xx/5xx on all failures in both cases then I can change to use the HTTP return code to dictate success. If not will have to try and parse both cases. Looking at the Node.js version that is what happens there.

Note: the `Content-Type` is wrong in both cases.

**Comment by glynhudson** [comment]
I've raised this issue with @TrystanLea, it's because emoncms.org is running a different (older) version than the local Emoncms. 

Would it be possible to handle either `ok` or `"success": true` as a positive result? This would work for all emoncms installs. This is probably more reliable than just looking for 2xx HTTP code.
