### ISSUE TITLE
Potentail webserver stability issues 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#61]
I've been unable to replicate myself but a number of users have reported connectivity issues using the ESP32 with the latest dev FW. One user reported being able to successfully control the EVSE via demand shaper (MQTT) while being unable to access the web UI. This indicates a possible issue only effecting the webserver component. 

https://community.openenergymonitor.org/t/esp-32-beta-loss-of-wifi-connection/13478/14

**Comment by chris1howell** [comment]
There are currently 21 stations with version 3.0.2 connected to the OpenEVSE MQTT server. They all seem to disconnect after a couple days and require a reboot to restore the Web interface and MQTT.

Not sure it is related but while working with Sam on the Tesla client he experienced a lot of WDT task crashes. The client would crash after a few minutes. The fix was a vTaskDelay(10) which now allows the tesla client to run a couple days.

  if (_respPhase == 1) {
      while (_client.available()) {
	vTaskDelay(10);
	_resp.respStr += _client.readString();
      }

**Comment by jeremypoulter** [comment]
Where is that code?

**Comment by chris1howell** [comment]
The code is here in the Tesla Client.

https://github.com/lincomatic/ESP32_WiFi_V3.x/blob/master/src/tesla_client.cpp

**Comment by jeremypoulter** [comment]
Ah, you have just highlighted that main reason why we use Mongoose and not the WiFiClientSecure ;-)

**Comment by jeremypoulter** [comment]
@MarkNinja I noticed this commit on your fork https://github.com/MarkNinja/ESP32_WiFi_V3.x/commit/ff9cc88176d59d968ccfdeddd73499601ec88cd2. Does this resolve similar issues to the ones highlighted here?

**Comment by MarkNinja** [comment]
Yes.  I believe my WiFi router was dropping the connection occasionally and the ESP32 would occasionally not be reachable.  Since my change to retry the WiFi connection when dropped I have not had the issue.

**Comment by jeremypoulter** [comment]
Hopefully this is closed now
